<?php
/**
 * TL_ROOT/system/modules/zibepla/languages/nl/default.php 
 * 
 * Contao extension: zibepla 1.2.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Andreas Gallien 
 * License   : Creative Commons (CC-by-nd) 
 * Author    : Andreas Gallien (gallien), http://www.zibepla.com 
 * Translator: Jane Roeleveld (jroelev6) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['availabilities'] = "Beschikbaarheidskalenders";
$GLOBALS['TL_LANG']['CTE']['availability']['0'] = "Beschikbaarheidskalender";
$GLOBALS['TL_LANG']['CTE']['availability']['1'] = "Voegt een beschikbaarheidskalender toe aan de pagina.";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['0'] = "Zondag";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['1'] = "Maandag";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['2'] = "Dinsdag";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['3'] = "Woensdag";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['4'] = "Donderdag";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['5'] = "Vrijdag";
$GLOBALS['TL_LANG']['ZIBEPLA']['DAYS']['6'] = "Zaterdag";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['0'] = "Januari";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['1'] = "Februari";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['2'] = "Maart";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['3'] = "April";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['4'] = "Mei";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['5'] = "Juni";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['6'] = "Juli";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['7'] = "Augustus";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['8'] = "September";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['9'] = "Oktober";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['10'] = "November";
$GLOBALS['TL_LANG']['ZIBEPLA']['MONTHS']['11'] = "December";
$GLOBALS['TL_LANG']['ZIBEPLA']['copyright_title_1'] = "Online Beschikbaarheidsplan";
$GLOBALS['TL_LANG']['ZIBEPLA']['copyright_anchor_1'] = "Contao Beschikbaarheidsplan";
$GLOBALS['TL_LANG']['ZIBEPLA']['copyright_title_2'] = "Beschikbaarheid en Reserveringssysteem";
$GLOBALS['TL_LANG']['ZIBEPLA']['copyright_anchor_2'] = "Zibepla";
 
?>
