<?php
/**
 * TL_ROOT/system/modules/zibepla/languages/nl/tl_content.php 
 * 
 * Contao extension: zibepla 1.2.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Andreas Gallien 
 * License   : Creative Commons (CC-by-nd) 
 * Author    : Andreas Gallien (gallien), http://www.zibepla.com 
 * Translator: Jane Roeleveld (jroelev6) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['zibepla_availability']['0'] = "Beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_content']['zibepla_availability']['1'] = "Selecteer een beschikbaarheidskalender.";
 
?>
