<?php
/**
 * TL_ROOT/system/modules/zibepla/languages/nl/tl_zibepla_availability.php 
 * 
 * Contao extension: zibepla 1.2.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Andreas Gallien 
 * License   : Creative Commons (CC-by-nd) 
 * Author    : Andreas Gallien (gallien), http://www.zibepla.com 
 * Translator: Jane Roeleveld (jroelev6) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_zibepla_availability']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['title']['1'] = "Voeg de titel van de beschikbaarheidskalendar bij.";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['maxMonths']['0'] = "Maximum aantal maanden";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['maxMonths']['1'] = "Hier kunt u de aantal maanden beperken.";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['monthsPerRow']['0'] = "Maanden per regel";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['monthsPerRow']['1'] = "De aantal maanden per regel.";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['tstamp']['0'] = "Wijzigingsdatum";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['tstamp']['1'] = "Tijd en datum laatste wijziging";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['title_legend'] = "Titel";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['deleteConfirm'] = "Het verwijderen van een kalender verwijdert tegelijkertijd alle beschikbaarheidsinformatie. Wilt u beschikbaarskalender ID %s verwijderen?";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['resetConfirm'] = "Het resetten van een kalender verwijdert tegelijkertijd alle beschikbaarheidsinformatie. Wilt u beschikbaarskalender ID %s resetten?";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['new']['0'] = "Nieuwe beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['new']['1'] = "Een nieuwe beschikbaarheidskalender aanmaken.";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['show']['0'] = "Gegevens van de beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['show']['1'] = "Toon de gegevens van beschikbaarheidskalender ID %s aan";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['edit']['0'] = "Beschikbaarheidskalender aanpassen";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['edit']['1'] = "Beschikbaarheidskalender ID%s aanpassen";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['copy']['0'] = "Kopie maken van beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['copy']['1'] = "Kopie maken van beschikbaarheidskalender ID %s";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['delete']['0'] = "Verwijder beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['delete']['1'] = "Verwijder beschikbaarheidskalender ID %s";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['item']['0'] = "Beheer beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['item']['1'] = "Beheer beschikbaarheidskalender ID %s";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['items']['0'] = "Beheer beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['items']['1'] = "Beheer beschikbaarheidskalender ID %s";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['reset']['0'] = "Reset beschikbaarheidskalender";
$GLOBALS['TL_LANG']['tl_zibepla_availability']['reset']['1'] = "Reset beschikbaarheidskalender ID %s";
 
?>
