<?php
/**
 * TL_ROOT/system/modules/zibepla/languages/nl/tl_zibepla_availability_item.php 
 * 
 * Contao extension: zibepla 1.2.1 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; 2010 Andreas Gallien 
 * License   : Creative Commons (CC-by-nd) 
 * Author    : Andreas Gallien (gallien), http://www.zibepla.com 
 * Translator: Jane Roeleveld (jroelev6) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['startDate']['0'] = "Aankomst datum";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['startDate']['1'] = "Aankomst datum in global time formaat toevoegen.";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['endDate']['0'] = "Vertrekdatum";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['endDate']['1'] = "Vertrekdatum datum in global time formaat toevoegen.";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['status']['0'] = "Status";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['status']['1'] = "Status van de periode";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['free'] = "vrij / beschikbaar";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['occupied'] = "bezet / niet beschikbaar";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['availability_period_legend'] = "Periode";
$GLOBALS['TL_LANG']['tl_zibepla_availability_item']['availability_calendar_legend'] = "Kalender";
 
?>
